name: Add Console Plugin metadata

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-and-update-project-fields:
    # Only run jobs if the feature branch is in your repo (not in a fork)
    # OR
    # it is an issue
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Kuadrant/projects/18
          github-token: ${{ secrets.PROJECT_METADATA_SECRET }}
        id: add-project  # Save the step output for item-id
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/Kuadrant/projects/18
          github-token: ${{ secrets.PROJECT_METADATA_SECRET }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Feature,Area
          field-values: Console Plugin,User Experience
